name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          # 根据项目需求设置 Node.js 版本
          node-version: ^18.18.0, ^20.17.0, or >=21.1.0

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          # 根据需要设置 pnpm 版本
          version: 9.14.0

      - name: Install dependencies
        run: pnpm i

      - name: Test
        run: pnpm run test

      - name: Build
        run: pnpm run build

      - name: Release
        run: pnpm run release
        env:
          # 发布脚本需要的 GitHub 令牌
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/**
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to npm
        if: success()
        run: pnpm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # 您的 npm 令牌
          ROSE_UI_LINT_TOKENS: ${{ secrets.ROSE_UI_LINT_TOKENS }}
